---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-admin
spec:
  selector:
    app: {{ .Values.app }}
    component: admin
    release: {{ .Release.Name }}
  ports:
  - name: admin
    port: 80
    targetPort: 80
