apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-api
type: Opaque
stringData:
  appsettings.json: |-
{{ tpl (.Files.Get (printf "configs/api/appsettings-%s.json" .Values.stage) | indent 4) .}}
  
  nlog.config: |-
{{ tpl (.Files.Get "configs/nlog.config" | indent 4) .}}