---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-api
spec:
  selector:
    app: {{ .Values.app }}
    component: api
    release: {{ .Release.Name }}
  ports:
  - name: api
    port: 80
    targetPort: 80